### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by inxomnyaa** [BajanVlogs/CellPE#1]
I am interested but have no idea what this plugin does.

**Comment by OfficialLilKev** [comment]
Ok will do

**Comment by inxomnyaa** [comment]
Oh so its like factions where you claim areas aand so on?

**Comment by OfficialLilKev** [comment]
Hey could you possibly help with the Guards like the making of the Guards and the command for it

**Comment by inxomnyaa** [comment]
Not for free, because i am quite busy. maybe for 15$?

**Comment by OfficialLilKev** [comment]
$15 whats your email?

**Comment by OfficialLilKev** [comment]
Like do you know CosmicPrisons that's what I'm trying to remake there cells plugin

**Comment by inxomnyaa** [comment]
i only know of the Cuboss network
