### ISSUE TITLE
Doesn’t Set Properly.

### ISSUE THREAD

**Issue by Dos-e** [BajanVlogs/CellPE#14]
My issue is that I set the first position then the second, and it works. But when I go above the cell, its saying the cell above is cell1 on /cell check and doesn't let me do anything until I purchase cell1.

**Comment by OfficialLilKev** [comment]
This has been fixed in the latest commit

**Comment by Dos-e** [comment]
Im pretty sure it hasn’t been fixed. All that was changed was the API.
