### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mikeygio10** [BajanVlogs/CellPE#21]
23.05 00:39:06 [Server] Server thread/INFO Enabling CellPE v2.0.3
23.05 00:39:06 [Server] INFO Fatal error: Class 'pocketmine\scheduler\PluginTask' not found in phar:///plugins/CellPE_dev-77.phar/src/Bajan/CellPE/task/ExpireTask.php on line 9
23.05 00:39:06 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
23.05 00:39:06 [Server] Server thread/EMERGENCY Please upload the "/crashdumps/Thu_May_23-00.39.06-UTC_2019.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
23.05 00:39:06 [Server] Server thread/EMERGENCY The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/2404886 or use the ID #2404886.

**Comment by Crypt97** [comment]
Use it https://github.com/Crypt97/CellPE
