### ISSUE TITLE
Found An Issue 

### ISSUE THREAD

**Issue by MTwinz** [BajanVlogs/CellPE#9]
Enabling CellPE v2.0.2
02.10 00:24:55 [Server] INFO Fatal error: Declaration of Bajan\CellPE\commands\MainCommand::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $cmd, $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in phar:///plugins/CellPE.phar/src/Bajan/CellPE/commands/MainCommand.php on line 23
02.10 00:24:55 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
02.10 00:24:55 [Server] Server thread/EMERGENCY Please upload the "/crashdumps/Mon_Oct_2-00.24.55-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by OfficialLilKev** [comment]
This has been fixed
